### ISSUE TITLE
When coming back into the app, credentials are not always requested - iOS 12.2

### ISSUE THREAD

**Issue by summertimeisfun** [RavenProject/ravenwallet-ios#101]
I did not see a configuration area to set timeout for authentication credentials so i assume it the reauthentication setting is hard coded somewhere or is not behaving correctly.  

When leaving the RVN Wallet, opening other applications and coming back into the wallet sometimes I was asked to authenticate, but not always.  

It is preferable to have a configuration setting to always authenticate.

**Comment by Menwitz** [comment]
Depend on how much you spend outside and if the iOS system kills the app or not.
