### ISSUE TITLE
Restore wallet with seed words and syncing - iOS 12.1.4

### ISSUE THREAD

**Issue by summertimeisfun** [RavenProject/ravenwallet-ios#112]
Installed latest rvn wallet from test flight on clean device and restored the seed words.  the device started to sync and got into sept and crashed.  Opened the wallet again and it's showing 16% synced on Jan 26th, 2018.

**Comment by TronBlack** [comment]
Please try again using the one that is currently in the App Store.

**Comment by TronBlack** [comment]
Fixed
