### ISSUE TITLE
Create CoinRequest button

### ISSUE THREAD

**Issue by Paulsky** [RavenProject/ravenwallet-ios#115]
It would be nice if there was a CoinRequest button added in the request view where you can generate a request, and send it by message and email. This way, the requester can share his request through multiple channels. And also, the receiver(**s**) can pay through multiple wallets (and QR code).

![button](https://user-images.githubusercontent.com/9481318/59913506-8865a700-9418-11e9-8acb-83f55832d030.PNG)

This can be achieved by adding a link to CoinRequest like this:

`https://coinrequest.io/create?coin=ravencoin&address=<address>&amount=<amount>&message=<message>` 

The message parameter is optional. Example:

`https://coinrequest.io/create?coin=ravencoin&address=RXdmuMghPQJ64uSGanSqPUPCE83cKjAA4B&amount=0.22&message=Please%20pay%20me%20for%20last%20night%27s%20dinner`

**Comment by jeroz1** [comment]
@ROSHiix @TronBlack interesting addition to make it easier to share payment requests.

**Comment by Menwitz** [comment]
I don't see a PR for this in iOS.

**Comment by Paulsky** [comment]
Please see this PR: https://github.com/RavenProject/ravenwallet-ios/pull/116

**Comment by a2hill** [comment]
As #116 has been merged, can this issue be closed?

**Comment by Paulsky** [comment]
Yes, I will close this issue.
