### ISSUE TITLE
QR scanner needs attention

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/ravenwallet-ios#120]
Users are reporting that sending and receiving assets using the QR scanner is not working for both iOS and Android. 

Samsung 8
iOS 13.1.2

**Comment by a2hill** [comment]
Tested on iOS 13.3 with version 1.2.0 , was able to send and receive assets. Is there any additional information?

**Comment by Menwitz** [comment]
Tested new version, couldn't find any problems.
