### ISSUE TITLE
Ability to reset RVN wallet if you lose PIN and 12 words.

### ISSUE THREAD

**Issue by Menwitz** [RavenProject/ravenwallet-ios#29]
prove ownership of the phone. touch id, face id or password.

**Comment by TronBlack** [comment]
This isn't a problem if FaceId or TouchId has been set.  But default is that these are not on.
Can't turn on by default because iOS needs to ask permission at the time you turn it on.

**Comment by TronBlack** [comment]
The reason this is a problem is that if you lose your PIN and 12-words, you cannot use RVN wallet at all because there is no way to erase/Reset to start over.
