### ISSUE TITLE
Fatal error at paper key page

### ISSUE THREAD

**Issue by akshaynexus** [RavenProject/ravenwallet-ios#4]
<img width="1887" alt="screen shot 2018-11-08 at 4 20 34 pm" src="https://user-images.githubusercontent.com/25401217/48201118-4ba9db80-e372-11e8-8095-8c6f9a787fef.png">
<img width="1159" alt="screen shot 2018-11-08 at 4 21 24 pm" src="https://user-images.githubusercontent.com/25401217/48201147-654b2300-e372-11e8-81fb-33340dca115a.png">

**Comment by akshaynexus** [comment]
the Simulator is running iOS 12.1

**Comment by Menwitz** [comment]
fixed with xcode 10 / swift 4.2 updates
https://github.com/RavenProject/ravenwallet-ios/commit/f312b3e5148d5fd4231f57a8b3de5d9f69de07d6

**Comment by akshaynexus** [comment]
ive cloned from the git repo,and pulled to check if there were any changes after i cloned,and i still get this error.Any ideas?

**Comment by akshaynexus** [comment]
im running XCode Version 10.1 (10B61) on macOS Mojave 10.14

**Comment by akshaynexus** [comment]
<img width="1617" alt="screen shot 2018-11-09 at 11 33 03 pm" src="https://user-images.githubusercontent.com/25401217/48286805-d7f1f680-e477-11e8-9e72-63e431a32cd7.png">
the same happens if i stop the app and try opening it again

**Comment by akshaynexus** [comment]
@ROSHiix

**Comment by akshaynexus** [comment]
nvm
