### ISSUE TITLE
Reissue - TRAVENCOINSONG4 - Set to qty 5 and did "generate address" - closes program.

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/ravenwallet-ios#54]

**Comment by ROSHiix** [comment]
This is something that needs deep changes of shared prefs structure, probably not gonna do it for this build.

**Comment by TronBlack** [comment]
What?  I just tried to Re-issue 5 more.  Why would that need deep changes?

**Comment by Menwitz** [comment]
sorry not this

**Comment by TronBlack** [comment]
Was able to duplicate twice, but not again.  Closing.  Watch for similar.
