### ISSUE TITLE
New wallet still does BIP32 m/0'/0 derivation if the flag is set.

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/ravenwallet-ios#85]
Dan's first address was derived from 
m/0'/0

**Comment by TronBlack** [comment]
How could this have happened if the old derivation has been removed?  Not a critical priority because it only affects internal testers.

**Comment by Menwitz** [comment]
He simply didn't wipe his wallet, there no flag in new code!

**Comment by TronBlack** [comment]
Public addresses are stored in the wallet.  This was the case for Dan.  The solution is to wipe the wallet.  Any future derivations are BIP44.  This will not be a problem after we solve for the internal testers only.
