### ISSUE TITLE
IOS V 1.1.0 (42)

### ISSUE THREAD

**Issue by gaetan29** [RavenProject/ravenwallet-ios#89]
Impossible to fully synchronise blockchain ... Keeps crashing after a while. I have remove app - even remove link with device .... still same issue.

**Comment by gaetan29** [comment]
I have re-installed it once more ... Sync stuck at 10% ... forever.

**Comment by akshaynexus** [comment]
maybe put log entries here,only then would devs be able to debug it

**Comment by gaetan29** [comment]
How to you get the log entry on IOS please?

**Comment by Menwitz** [comment]
pushing a new version that will connect to old nodes even if assets MSGing protocol doesn't comply.
70020 isn't widely adopted yet.

**Comment by gaetan29** [comment]
Same issue under Version 1.1.1 (47)
